// This is the database schema for my bwe database

Table exercise_muscles {
  id int [pk, increment]
  exercise_id int [ref: > exercises.id]
  muscle_id int [ref: > muscles.id]
  intensity int
}

Table exercises {
  id int [pk, increment]
  name varchar
  type varchar
  difficulty varchar
}

Table muscles {
  id int [pk, increment]
  name varchar
  type varchar
}

Table progressions {
  id int [pk, increment]
  exercise_id int [ref: > exercises.id]
  sequence_order int
  threshold int
}

Table user_workouts {
  id int [pk, increment]
  user_id int [ref: > users.id]
  workout_id int [ref: > workouts.id]
}

Table users {
  id int [pk, increment]
  name varchar
  email varchar [unique]
  password varchar
}

Table workout_log_items {
  id int [pk, increment]
  workout_log_id int [ref: > workout_logs.id]
  exercise_type varchar
  exercise_id int [ref: > exercises.id]
  exercise_time int
  reps int
  warmup boolean [default: false]
}

Table workout_logs {
  id int [pk, increment]
  user_id int [ref: > users.id]
  workout_id int [ref: > workouts.id]
  start_time datetime
  end_time datetime
}

Table workout_sequences {
  id int [pk, increment]
  workout_id int [ref: > workouts.id]
  type varchar
  exercise_id int [ref: > exercises.id]
  seconds int
  warmup boolean [default: false]
}

Table workouts {
  id int [pk, increment]
  name varchar
  user_id int [ref: > users.id]
  is_public boolean
}
