Table exercises {
id int [pk, increment]
name varchar(255)
type varchar(255)
difficulty varchar(255)
}

Table muscles {
id int [pk, increment]
name varchar(255)
type varchar(255)
}

Table exercise_muscles {
id int [pk, increment]
exercise_id int [ref: > exercises.id]
muscle_id int [ref: > muscles.id]
intensity int
}

Table progressions {
id int [pk, increment]
exercise_id int [ref: > exercises.id]
progression_exercise_id int [ref: > exercises.id]
sequence_order int
next_exercise_id int [ref: > exercises.id]
threshold int
}

Table users {
id int [pk, increment]
name varchar(255)
email varchar(255) [unique]
password varchar(255)
is_admin tinyint
}

Table workouts {
id int [pk, increment]
name varchar(255)
user_id int [ref: > users.id]
is_public int
}

Table user_workouts {
id int [pk, increment]
user_id int [ref: > users.id]
workout_id int [ref: > workouts.id]
}

Table workout_logs {
id int [pk, increment]
user_id int [ref: > users.id]
workout_id int [ref: > workouts.id]
start_time datetime
end_time datetime
}

Table workout_sequences {
id int [pk, increment]
workout_id int [ref: > workouts.id]
type varchar(255)
exercise_id int [ref: > exercises.id]
seconds int
warmup tinyint
}

Table workout_log_items {
id int [pk, increment]
workout_log_id int [ref: > workout_logs.id]
exercise_type varchar(45)
exercise_id int [ref: > exercises.id]
exercise_time int
reps int
warmup tinyint [default: 0]
}

Table achievements {
  id int [pk, increment] 
  name varchar(45) 
  type varchar(45) 
  level int
}

Table user_selected_workouts {
  user_id int [pk] 
  workout_id int [pk]
}